"""Add fields for Phase 2 CMS

Revision ID: 052c36e7ecc4
Revises: 
Create Date: 2026-02-17 08:09:31.724584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052c36e7ecc4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_news_is_active'), 'news', ['is_active'], unique=False)
    op.add_column('portfolio', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('portfolio', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('portfolio', sa.Column('display_order', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_portfolio_is_active'), 'portfolio', ['is_active'], unique=False)
    op.create_index(op.f('ix_portfolio_service_id'), 'portfolio', ['service_id'], unique=False)
    op.create_foreign_key(None, 'portfolio', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.add_column('testimonials', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_testimonials_is_active'), 'testimonials', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonials_is_active'), table_name='testimonials')
    op.drop_column('testimonials', 'is_active')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_column('products', 'category')
    op.drop_constraint(None, 'portfolio', type_='foreignkey')
    op.drop_index(op.f('ix_portfolio_service_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_is_active'), table_name='portfolio')
    op.drop_column('portfolio', 'display_order')
    op.drop_column('portfolio', 'is_active')
    op.drop_column('portfolio', 'service_id')
    op.drop_index(op.f('ix_news_is_active'), table_name='news')
    op.drop_column('news', 'is_active')
    # ### end Alembic commands ###
